# -*- coding: utf-8 -*-
"""Friends_Series_EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WyRFZcHvB2EoKJ7mjC2ChsJLan0sd6ao
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
# %matplotlib inline
warnings.filterwarnings('ignore')

friends = pd.read_csv('/content/sample_data/friends_episodes_v2.csv')

friends.head(5)

friends.tail(5)

friends.loc[233,'Episode_Title']="The Last One I"
friends.loc[234,'Episode_Title']="The Last One II"

friends.tail(5)

friends.duplicated().sum()

friends.info()

friends['Season']= friends['Season'].astype("object")

friends.info()

friends.shape

print("The show started in {} and ended in {}".format(min(friends['Year_of_prod']),max(friends['Year_of_prod'])))

friends['Season'].value_counts().sort_index()

plt.figure(figsize=(10,5))
plt.xlabel("Season")
plt.title("Count of Episodes")
sns.countplot(x = "Season", data = friends,palette='inferno')

season_duration = friends.groupby('Season')['Duration'].sum().to_frame().reset_index()
season_duration

plt.figure(figsize=(10,5))
plt.xlabel("Duration")
plt.ylabel("Season")
plt.title("Total Duration of each Season")
sns.barplot(x = season_duration.Season, y = season_duration.Duration,palette='mako')
plt.xticks(fontsize=12)
plt.yticks(fontsize=12)
plt.ylim(300, 600)

season_pop_epi = friends[['Episode_Title', 'Stars']].sort_values('Stars', ascending=False).head(10).reset_index(drop=True)
season_pop_epi

plt.figure(figsize=(10,5))
sns.barplot(y=season_pop_epi.Episode_Title, x=season_pop_epi.Stars, palette='twilight', orient='h')
plt.title('Top 10 High-Rated Episodes', fontsize=15)
plt.xlabel('IMDB Stars')
plt.ylabel('Episodes')
plt.xticks(fontsize=12)
plt.yticks(fontsize=12)
plt.xlim(9, 10)

director_count = friends.groupby("Director").Episode_Title.count().sort_values(ascending=False)
director_count

director_count.count()

top10_dir = director_count.head(10).reset_index()
top10_dir

plt.figure(figsize=(18,5))
sns.barplot(x=top10_dir['Director'], y=top10_dir['Episode_Title'], palette='Oranges')
plt.title('Top 10 High-Rated Episodes', fontsize=15)
plt.xlabel('Directed By')
plt.ylabel('No Of Episodes')

#Gary Halvorson and Kevin Bright has directed the maximum no of episodes, 54 each.
#
#Following are the director who directed only 1 episode

director_1 = director_count.reset_index()
director_1.columns= ["Director","Episode Count"]

director_1 = director_1[director_1['Episode Count'] == 1]
director_1

Director_Rating = friends.groupby("Director").Stars.agg(['count','mean']).sort_values(by="mean")
print(Director_Rating)

#   From this we can observe that Todd Holland has least average rating and
#   Joe Regalbuto has the highest rating.